swagger: "2.0"
info:
  description: "Wishox API Dobcumentation; It's WIP"
  version: "0.0.0"
  title: "Wishbox"
host: "37.32.10.55:8000"
basePath: /api/V0.0.0
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: access
tags:
  - name: "AUTH"
    description: "Authentication"
schemes:
  - "https"
  - "http"
paths:
  # AUTH
  /auth/otp/:
    $ref: "./auth/otp.yaml"
  /auth/otp/verify/:
    $ref: "./auth/verify.yaml"
  /auth/otp/refresh/:
    $ref: "./auth/refresh.yaml"
  
  # Profile
  /profile/:
    $ref: "./profile/profile.yaml"
  /profile/wishlist/:
    $ref: "./profile/wishlist.yaml"
  /profile/wishlist/{id}/:
    $ref: "./profile/update_wishlist.yaml"
  
  # Storage
  /storage/upload/:
    $ref: "./storage/upload.yaml"

  # Wish
  /wishlist/{id}/:
    $ref: "./wishlist/wishlist.yaml"
  /wishlist/{id}/wish/{wishid}/:
    $ref: "./wishlist/wish.yaml"
  /wishlist/{id}/wish/{wishid}/request/:
    $ref: "./wishlist/request.yaml"
  
