# Generated by Django 5.1.4 on 2025-10-16 16:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
        ("wishlist", "0002_wish"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousFriend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nickname", models.CharField(max_length=150, verbose_name="nickname")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "anonymous_friend",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservation_requests",
                        to="wishlist.anonymousfriend",
                        verbose_name="anonymous_friend",
                    ),
                ),
                (
                    "friend",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservation_requests",
                        to="profile.profile",
                        verbose_name="friend",
                    ),
                ),
                (
                    "wish",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservation_requests",
                        to="wishlist.wish",
                        verbose_name="wish",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="wish",
            name="accepted_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_wish",
                to="wishlist.reservationrequest",
            ),
        ),
    ]
