from src.utils.fakers.anonymous_friend import AnonymousFriendFactory
from src.utils.fakers.avatar import AvatarFactory
from src.utils.fakers.avatar_color import AvatarColorsFactory
from src.utils.fakers.avatar_widgets import AvatarWidgetsFactory
from src.utils.fakers.contact_us import ContactUsFactory
from src.utils.fakers.fake_image import fake_image
from src.utils.fakers.media import MediaModelFactory
from src.utils.fakers.profile import ProfileFactory
from src.utils.fakers.user import UserFactory
from src.utils.fakers.wishes import WishFactory
from src.utils.fakers.wishlist import WishlistFactory
