class ErrorEnum:
    class SendOneTimePassword:
        PHONE_NUMBER_IS_EMPTY = "SEND_OTP_PHONE_NUMBER_IS_EMPTY"
        OTP_ALREADY_SENT = "SEND_OTP_OTP_ALREADY_SENT"
        INVALID_PHONE_NUMBER = "SEND_OTP_USER_BLOCKED"

    class Authentication:
        UNAUTHORIZED = "AUTHENTICATION_UNAUTHORIZED"
        FORBIDDEN = "AUTHENTICATION_FORBIDDEN"

    class RefreshToken:
        REFRESH_IS_EMPTY = "REFRESH_TOKEN_REFRESH_IS_EMPTY"
        TOKEN_IS_NOT_VALID = "REFRESH_TOKEN_TOKEN_IS_NOT_VALID"
        USER_DOES_NOT_EXIST = "REFRESH_TOKEN_USER_DOES_NOT_EXIST"

    class VerifyOneTimePassword:
        OTP_ID_IS_EMPTY = "VERIFY_OTP_OTP_ID_IS_EMPTY"
        OTP_CODE_IS_EMPTY = "VERIFY_OTP_OTP_CODE_IS_EMPTY"
        INAVLID_OTP = "VERIFY_OTP_INVALID_OTP"

    class Services:
        INVALID_USER_ID = "SERVICE_INVALID_USER_ID"

    class Profile:
        PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
        INVALID_AVATAR_SETTINGS = "INVALID_AVATAR_SETTINGS"
        AVATAR_NOT_FOUND = "AVATAR_NOT_FOUND"

    class Wishlist:
        WISHLIST_NOT_FOUND = "WISHLIST_NOT_FOUND"
        WISH_NOT_FOUND = "WISH_NOT_FOUND"
        NOT_WISHLIST_OWNER = "NOT_WISHLIST_OWNER"

    class HTTP:
        METHOD_NOT_ALLOWED = "HTTP_METHOD_NOT_ALLOWED"
        THROTTLED = "HTTP_THROTTLED"

    class UploadFile:
        FILE_IS_EMPTY = "FILE_IS_EMPTY"
