# Generated by Django 5.1.4 on 2025-11-01 20:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, null=True, verbose_name="settings"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                        verbose_name="profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvatarWidgets",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Face", "Face"),
                            ("Tops", "Tops"),
                            ("Ear", "Ear"),
                            ("Earrings", "Earrings"),
                            ("Eyebrows", "Eyebrows"),
                            ("Eyes", "Eyes"),
                            ("Nose", "Nose"),
                            ("Glasses", "Glasses"),
                            ("Mouth", "Mouth"),
                            ("Beard", "Beard"),
                            ("Clothes", "Clothes"),
                        ],
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="is premium"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="widget_image",
                        to="storage.mediamodel",
                        verbose_name="image",
                    ),
                ),
            ],
        ),
    ]
