# Generated by Django 5.1.4 on 2025-11-08 18:10

import colorfield.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_avatar_avatarwidgets"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarColors",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FFFFFFFF",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="color",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="updated at"),
                ),
            ],
        ),
    ]
