# Generated by Django 5.1.4 on 2025-11-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_avatarcolors"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatarwidgets",
            name="colors",
            field=models.ManyToManyField(
                blank=True,
                related_name="widgets",
                to="profile.avatarcolors",
                verbose_name="colors",
            ),
        ),
    ]
