name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Login to docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
      -
          name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./build/Dockerfile
            push: true
            tags: theparsa/wishbox:latest